name: Update blog post

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 1 * * *'

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://feeds.feedburner.com/ScriptInside"
