name: Update blog post


on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: gautamkrishnar/blog-post-workflow@1.0.4
      with:
        gh_token: ${{ github.token }}
        max_post_count: 10
        readme_path: README.md
        feed_list: http://feeds.feedburner.com/ScriptInside
